services:
  taskmasterapi:
    environment:
      - ConnectionStrings__DefaultConnection=Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - Kestrel__Certificates__Default__Password=your-password
    ports:
      - '80:80'
      - '443:443'
    networks:
      - task_manager_network
    volumes:
      - ./certs:/https:ro
        
  pgAdmin:
    ports:
      - 8080:80
    volumes:
      - pgAdmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - task_manager_network