services:
  taskmasterapi:
    container_name: task_manager_api
    build:
      context: .
      dockerfile: TaskMasterAPI/Dockerfile
    restart: always
    
  frontend:
    container_name: taskmasterui
    build:
      context: .
      dockerfile: TaskMasterUI/Dockerfile
    restart: always

networks:
  task_manager_network:

volumes:
  pgAdmin-data: