services:
  taskmasterapi:
    environment:
      - ConnectionStrings__DefaultConnection=Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - Kestrel__Certificates__Default__Password=your-password
    ports:
      - '80:80'
      - '443:443'
    networks:
      - task_manager_network
    volumes:
      - ./certs:/https:ro
      
  frontend:
    ports:
      - "3000:80"
    depends_on:
      - taskmasterapi
    networks:
      - task_manager_network